---
- name: create minio group
  group:
    name: "{{ minio_group }}"
    state: present

- name: create minio user
  user:
    name: "{{ minio_user }}"
    group: "{{ minio_group }}"
    shell: /bin/bash

- name: download minio server
  get_url:
    url: "{{ minio_server_download_url }}"
    dest: "{{ minio_server_bin }}"
    owner: "{{ minio_user }}"
    group: "{{ minio_group }}"
    mode: 0755

- name: generate the minio server envfile
  template:
    src: minio.env.j2
    dest: "{{ minio_server_envfile }}"
  notify: restart minio

- name: create the minio server systemd config
  template:
    src: minio.service.j2
    dest: "{{ systemd_units_dir }}/minio.service"

- name: enable and start the minio service
  service:
    name: minio
    state: started
    enabled: yes
