---
- name: Create minio container
  docker_container:
    name: minio1
    image: minio/minio
    volumes:
      - /tmp/data:/data
    ports:
      - "9005:9000"
    command: server /data
    env:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
